CREATE TABLE TIPO_EMPLEADO (
    tipo_empleado NUMBER(2)
    GENERATED ALWAYS AS IDENTITY
    MINVALUE 1 MAXVALUE 99 
    START WITH 1 INCREMENT BY 1
    CONSTRAINT PK_TIPO_EMP PRIMARY KEY, 
    desc_tipo_empleado VARCHAR2(25) NOT NULL
);

CREATE TABLE EMPLEADO (
    id_empleado NUMBER(5) GENERATED ALWAYS AS IDENTITY
    MINVALUE 1 
    MAXVALUE 99999 
    START WITH 1 
    INCREMENT BY 1
    CONSTRAINT PK_EMPLEADO PRIMARY KEY,
    numrut NUMBER(10) NOT NULL,
    dvrut VARCHAR2(1) NOT NULL,
    primer_nombre VARCHAR2(20) NOT NULL,
    snombre VARCHAR2(20),
    appaterno VARCHAR2(20) NOT NULL,
    apmaterno VARCHAR2(20) NOT NULL,
    fecha_contrato DATE NOT NULL,
    tipo_empleado NUMBER(2) 
    CONSTRAINT FK_EMPLEADO REFERENCES TIPO_EMPLEADO(tipo_empleado)
);

CREATE TABLE VENTAS (
    nro_boleta NUMBER(8) CONSTRAINT PK_VENTAS PRIMARY KEY,
    id_empleado NUMBER(5)
    CONSTRAINT FK_ID_EMPLEADO REFERENCES EMPLEADO(id_empleado),
    fecha_boleta DATE NOT NULL,
    monto_total NUMBER(8) NOT NULL
);

CREATE TABLE COMISION_VENTAS (
    nro_boleta NUMBER(8) 
    CONSTRAINT PK_COM_VENTAS PRIMARY KEY,
    monto_comision NUMBER(8) NOT NULL,
    CONSTRAINT FK_COM_VENTAS FOREIGN KEY (nro_boleta)
    REFERENCES VENTAS(nro_boleta)
);