-- Creación de tablas

CREATE SEQUENCE seq_volumen
    START WITH 10000
    INCREMENT BY 10;

CREATE TABLE FACULTAD (
    codFacultad NUMBER(2) NOT NULL,
    nombreFacultad VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_FACULTAD PRIMARY KEY (codFacultad)
);

CREATE TABLE CARRERA (
    codCarrera NUMBER(2) NOT NULL,
    nombreCarrera VARCHAR2(50) NOT NULL,
    codFacultad NUMBER(2) NOT NULL,
    CONSTRAINT PK_CARRERA PRIMARY KEY (codCarrera),
    CONSTRAINT FK_CARRERA_FACULTAD FOREIGN KEY (codFacultad) REFERENCES FACULTAD(codFacultad)
);

CREATE TABLE CAMPUS (
    codCampus NUMBER(2),
    nombreCampus VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_CAMPUS PRIMARY KEY (codCampus)
);

CREATE TABLE AUTOR (
    codAutor NUMBER(4) NOT NULL,
    nombreAutor VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_AUTOR PRIMARY KEY (codAutor)
);

CREATE TABLE EDITORIAL (
    codEditorial NUMBER(4) NOT NULL,
    nombreEditorial VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_EDITORIAL PRIMARY KEY (codEditorial)
);

CREATE TABLE TITULO (
    codTitulo NUMBER(6) NOT NULL,
    titulo VARCHAR2(30) NOT NULL,
    ISBN NUMBER(7) NOT NULL,
    anoPublicacion NUMBER(4),
    codEditorial NUMBER(4) NOT NULL,
    CONSTRAINT PK_TITULO PRIMARY KEY (codTitulo),
    CONSTRAINT FK_TITULO_EDITORIAL FOREIGN KEY (codEditorial) REFERENCES EDITORIAL(codEditorial),
    CONSTRAINT ISBN_UNIQUE UNIQUE (ISBN)
);

CREATE TABLE DET_AUTOR (
    codAutor NUMBER(4) NOT NULL,
    codTitulo NUMBER(6) NOT NULL,
    CONSTRAINT PK_DET_AUTOR PRIMARY KEY (codAutor, codTitulo),
    CONSTRAINT FK_DET_AUTOR_AUTOR FOREIGN KEY (codAutor) REFERENCES AUTOR(codAutor),
    CONSTRAINT FK_DET_AUTOR_TITULO FOREIGN KEY (codTitulo) REFERENCES TITULO(codTitulo)
);

CREATE TABLE BIBLIOTECA (
    codBiblioteca NUMBER(2) NOT NULL,
    nombreBiblioteca VARCHAR2(50) NOT NULL,
    mtsCuadrados NUMBER(4) NOT NULL,
    capacidad NUMBER(3) NOT NULL,
    codCampus NUMBER(2) NOT NULL,
    CONSTRAINT PK_BIBLIOTECA PRIMARY KEY (codBiblioteca),
    CONSTRAINT FK_BIBLIOTECA_CAMPUS FOREIGN KEY (codCampus) REFERENCES CAMPUS(codCampus)
);

CREATE TABLE VOLUMEN (
    codVolumen NUMBER(6) DEFAULT seq_volumen.NEXTVAL,
    fechaCreacion DATE NOT NULL,
    fechaUltimoInventario DATE,
    estado VARCHAR2(50) NOT NULL,
    codBiblioteca NUMBER(2) NOT NULL,
    codTitulo NUMBER(6) NOT NULL,
    CONSTRAINT PK_VOLUMEN PRIMARY KEY (codVolumen),
    CONSTRAINT FK_VOLUMEN_BIBLIOTECA FOREIGN KEY (codBiblioteca) REFERENCES BIBLIOTECA(codBiblioteca),
    CONSTRAINT FK_VOLUMEN_TITULO FOREIGN KEY (codTitulo) REFERENCES TITULO(codTitulo)
);

CREATE TABLE ESTUDIANTE (
    rut NUMBER(9) CONSTRAINT PK_ESTUDIANTE PRIMARY KEY,
    dv NUMBER(1) NOT NULL,
    pNombre VARCHAR2(50),
    sNombre VARCHAR2(50),
    apPaterno VARCHAR2(50) NOT NULL,
    apMaterno VARCHAR2(50) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    celular NUMBER(9) NOT NULL
);

CREATE TABLE PRESTAMO (
    idPrestamo NUMBER(6) GENERATED ALWAYS AS IDENTITY
    MINVALUE 1 MAXVALUE 999999
    START WITH 1 INCREMENT BY 1,
    estudianteRut NUMBER(9) NOT NULL,
    codVolumen NUMBER(6) NOT NULL,
    fechaPrestamo DATE NOT NULL,
    CONSTRAINT PK_PRESTAMO PRIMARY KEY (idPrestamo),
    CONSTRAINT FK_PRESTAMO_ESTUDIANTE FOREIGN KEY (estudianteRut) REFERENCES ESTUDIANTE(rut),
    CONSTRAINT FK_PRESTAMO_VOLUMEN FOREIGN KEY (codVolumen) REFERENCES VOLUMEN(codVolumen)
);

CREATE TABLE PRESTAMO_CARRERA_MES (
    idPrestamo NUMBER(6) GENERATED ALWAYS AS IDENTITY
    MINVALUE 1 MAXVALUE 999999
    START WITH 1 INCREMENT BY 1,
    codCarrera NUMBER(2),
    mes NUMBER(2) NOT NULL,
    anio NUMBER(4) NOT NULL,
    CONSTRAINT FK_PCM_PRESTAMO FOREIGN KEY (idPrestamo) REFERENCES PRESTAMO(idPrestamo),
    CONSTRAINT FK_PCM_CARRERA FOREIGN KEY (codCarrera) REFERENCES CARRERA(codCarrera),
    CONSTRAINT PK_PCM PRIMARY KEY (codCarrera, mes, anio)
);
